name: test

on:
  # トリガーを決める
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
    - name: Specify_outputs
      shell: bash
      run: |
        case ${{ github.base_ref }} in
          "develop" ) echo "::set-output name=DEPLOY_ENV::dev"
                      echo "::set-output name=DEPLOY_BRANCH::origin/develop" ;;
          "master" ) echo "::set-output name=DEPLOY_ENV::prod"
                     echo "::set-output name=DEPLOY_BRANCH::origin/master" ;;
          * ) echo "::set-output name=DEPLOY_ENV::none" ;;
        esac
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awscli
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      # ユーザ＆ロールを決める
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
        role-duration-seconds: 1200
        role-session-name: nasu
    - name: deploy
      shell: bash
      run: bash deploy/deploy-test.bash ${{ steps.Specify_outputs.outputs.DEPLOY_ENV }} ${{ steps.Specify_outputs.outputs.DEPLOY_BRANCH }}
