name: test

on:
  # 手動実行
  workflow_dispatch:
    inputs:
      environment:
        description: 'target env'
        required: true
        default: 'staging'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Specify outputs
      id: set_output
      shell: bash
      run: |
        case ${{ github.event.inputs.environment }} in
          "dev" ) echo "::set-output name=DEPLOY_ENV::dev"
                      echo "::set-output name=DEPLOY_BRANCH::origin/develop" ;;
          "prod" ) echo "::set-output name=DEPLOY_ENV::prod"
                     echo "::set-output name=DEPLOY_BRANCH::origin/master" ;;
          * ) echo "::set-output name=DEPLOY_ENV::none" ;;
        esac
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awscli
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      # ユーザ＆ロールを決める
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
        role-duration-seconds: 1200
        role-session-name: nasu
    - name: deploy
      shell: bash
      run: bash deploy/deploy-test.bash ${{ steps.set_output.outputs.DEPLOY_ENV }} ${{ steps.set_output.outputs.DEPLOY_BRANCH }}
